apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx-app
  name: deploy-nginx
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: myappl
  template: 
    metadata: 
      labels: 
        app: myappl
      name: myappl-pod
    spec: 
      containers: 
        - 
          image: nginx
          name: nginx-container
          ports: 
            - 
              containerPort: 80
      nodeName: node02

