apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: myappl
  name: myappl-pod
spec: 
  containers: 
    - 
      image: nginx
      name: nginx-container
      ports: 
        - 
          containerPort: 80
  nodeName: node02

