apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: myapp
  name: myapp-pod
spec: 
  containers: 
    - 
      image: nginx
      name: nginx-container
      ports: 
        - 
          containerPort: 80
  nodeName: node01

